### ISSUE TITLE
`@clerk/nextjs@5.2.0` cause a build warning in NextJS middleware

### ISSUE THREAD

**Issue by arvinxx** [clerk/javascript#3660]
### Preliminary Checks

- [X] I have reviewed the documentation: https://clerk.com/docs
- [X] I have searched for existing issues: https://github.com/clerk/javascript/issues
- [X] I have not already reached out to Clerk support via email or Discord (if you have, no need to open an issue here)
- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Clerk. Please ask questions in our Discord community: https://clerk.com/discord.

### Reproduction

https://github.com/lobehub/lobe-chat/tree/reproduction/clerk-nextjs-5.2.0

### Publishable key

no need, it's a build time issue

### Description

here is the build log:
```
   Creating an optimized production build ...
 ✓ (pwa) Compiling for server...
 ✓ (pwa) Compiling for server...
 ✓ (pwa) Compiling for client (static)...
 ○ (pwa) Service worker: /vercel/path1/public/sw.js
 ○ (pwa)   URL: /sw.js
 ○ (pwa)   Scope: /
 ⚠ Compiled with warnings
./node_modules/@clerk/nextjs/dist/esm/server/clerkMiddleware.js
A Node.js module is loaded ('async_hooks' at line 3) which is not supported in the Edge Runtime.
Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime
Import trace for requested module:
./node_modules/@clerk/nextjs/dist/esm/server/clerkMiddleware.js
./node_modules/@clerk/nextjs/dist/esm/server/index.js
./node_modules/@clerk/shared/dist/chunk-RSOCGYTF.mjs
A Node.js API is used (MessageEvent at line: 28) which is not supported in the Edge Runtime.
Learn more: https://nextjs.org/docs/api-reference/edge-runtime
Import trace for requested module:
./node_modules/@clerk/shared/dist/chunk-RSOCGYTF.mjs
./node_modules/@clerk/shared/dist/index.mjs
./node_modules/@clerk/nextjs/dist/esm/server/utils.js
./node_modules/@clerk/nextjs/dist/esm/server/clerkClient.js
./node_modules/@clerk/nextjs/dist/esm/server/index.js
```

you can see the error from `@clerk/nextjs`. please remove this usage: 

https://github.com/clerk/javascript/blob/1a704ed9de3ad222ff17d10cb383639b2fc038b9/packages/nextjs/src/server/clerkMiddleware.ts#L10

### Environment

```Shell
Next.JS: 14.2.4
@nextjs/clerk: >=5.2.0
```

**Comment by LauraBeatris** [comment]
Hi @arvinxx, thanks for raising the issue! We're working on a fix for it and it should be released soon.

**Comment by LauraBeatris** [comment]
@arvinxx The fix has been merged and will soon release a patch for `@clerk/nextjs`! 🫡

**Comment by shawnesquivel** [comment]
Hi @LauraBeatris  I'm still facing what seems to be the same issue in my project

```
    "@clerk/nextjs": "^5.2.3",
    "next": "14.1.3",

```

middleware.ts
```
import { clerkMiddleware } from "@clerk/nextjs/server";

export default clerkMiddleware();

console.log("middleware called");

export const config = {
  matcher: ["/((?!.*\\..*|_next).*)", "/", "/(api|trpc)(.*)"],
};

```


Error
```
 ⨯ node:async_hooks
Module build failed: UnhandledSchemeError: Reading from "node:async_hooks" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
Import trace for requested module:
node:async_hooks
./node_modules/@clerk/nextjs/dist/esm/server/clerkMiddleware.js
./node_modules/@clerk/nextjs/dist/esm/server/index.js
./src/app/profile/[[...profile]]/page.jsx
```

**Comment by LauraBeatris** [comment]
> Hi @LauraBeatris I'm still facing what seems to be the same issue in my project
> 
> ```
>     "@clerk/nextjs": "^5.2.3",
>     "next": "14.1.3",
> ```
> 
> middleware.ts
> 
> ```
> import { clerkMiddleware } from "@clerk/nextjs/server";
> 
> export default clerkMiddleware();
> 
> console.log("middleware called");
> 
> export const config = {
>   matcher: ["/((?!.*\\..*|_next).*)", "/", "/(api|trpc)(.*)"],
> };
> ```
> 
> Error
> 
> ```
>  ⨯ node:async_hooks
> Module build failed: UnhandledSchemeError: Reading from "node:async_hooks" is not handled by plugins (Unhandled scheme).
> Webpack supports "data:" and "file:" URIs by default.
> You may need an additional plugin to handle "node:" URIs.
> Import trace for requested module:
> node:async_hooks
> ./node_modules/@clerk/nextjs/dist/esm/server/clerkMiddleware.js
> ./node_modules/@clerk/nextjs/dist/esm/server/index.js
> ./src/app/profile/[[...profile]]/page.jsx
> ```

Hey @shawnesquivel! Looking into this.

**Comment by shawnesquivel** [comment]
Thanks @LauraBeatris . I tried making a minimal repro with no luck – it seems to work on a fresh repo. 

As an interim, here's what I've tried on my own project:
- cleared `.next` directory, `node_modules` folders
- verified that other Clerk components can be imported properly and used.
```
import { SignedOut, SignedIn, SignInButton } from "@clerk/nextjs";
```
- pinpointed the error comes when I import this line of code:
```
import { auth, currentUser } from "@clerk/nextjs/server";
```

**Comment by shawnesquivel** [comment]
@LauraBeatris  I can confirm that this issue has presently went away when I stopped using it in a client component, denoted by the "use client" directive.

I wonder if it could be made more clear through the documentation that the {auth, currentUser} methods should not be used in client components at all.

**Comment by LauraBeatris** [comment]
> @LauraBeatris I can confirm that this issue has presently went away when I stopped using it in a client component, denoted by the "use client" directive.
> 
> The docs do say it should be able to be used in client components though, so I think it's still a bug worth noting.
> 
> https://clerk.com/docs/references/nextjs/read-session-data

Hi @shawnesquivel! [`auth()`](https://clerk.com/docs/references/nextjs/auth) and [`currentUser()`](https://clerk.com/docs/references/nextjs/current-user) are server-side APIs only to be used from Next.js app router. 

On client components, `useAuth` should be used instead: https://clerk.com/docs/references/nextjs/read-session-data#client-side.

**Comment by LauraBeatris** [comment]
Hey everyone! We're actively working to improve the error message when server-side helpers are used in a client-side context.

I'll re-open this issue again and related to a PR soon.

**Comment by sonnguyen-propte** [comment]
Hi @LauraBeatris @shawnesquivel , I'm facing the same issue. Is there a way to resolve this?

**Comment by philosofonusus** [comment]
I have the same issue
